# Generated by Django 6.1 on 2026-08-25 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='投稿标题')),
                ('author_name', models.CharField(max_length=80, verbose_name='投稿人')),
                ('contact', models.CharField(blank=True, max_length=160, verbose_name='联系方式')),
                ('category', models.CharField(choices=[('story', '家族故事'), ('showcase', '买家秀 / 搭配指南'), ('memory', '老照片与城市记忆')], default='story', max_length=20, verbose_name='投稿类型')),
                ('story', models.TextField(verbose_name='投稿内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ugc/%Y/%m/', verbose_name='图片')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('featured', models.BooleanField(default=False, verbose_name='精选展示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户共创投稿',
                'verbose_name_plural': '用户共创投稿',
                'ordering': ('-featured', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=80, verbose_name='页面标识')),
                ('anchor', models.CharField(blank=True, max_length=80, verbose_name='内容锚点')),
                ('author_name', models.CharField(max_length=80, verbose_name='留言昵称')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment', verbose_name='回复对象')),
            ],
            options={
                'verbose_name': '评论与回复',
                'verbose_name_plural': '评论与回复',
                'ordering': ('-created_at',),
            },
        ),
    ]
